# Generated by Django 3.1.2 on 2021-07-18 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=256, unique=True)),
                ('passwd', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=128)),
                ('on_job', models.DateField(default=datetime.date.today)),
                ('salary', models.PositiveIntegerField()),
                ('annual', models.PositiveSmallIntegerField(default=0)),
                ('annual_left', models.PositiveSmallIntegerField(default=0)),
                ('labor', models.PositiveSmallIntegerField(default=1)),
                ('health', models.PositiveSmallIntegerField(default=1)),
                ('family', models.PositiveSmallIntegerField(default=0)),
                ('retirement', models.PositiveSmallIntegerField(default=1)),
                ('self_percent', models.PositiveSmallIntegerField(default=0)),
                ('retire_self', models.PositiveSmallIntegerField(default=0)),
                ('boss', models.BooleanField(default=False)),
                ('manager', models.BooleanField(default=False)),
                ('hr', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['on_job'],
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2021)),
                ('month', models.PositiveSmallIntegerField(default=7)),
                ('over_13', models.PositiveSmallIntegerField(default=0)),
                ('over_23', models.PositiveSmallIntegerField(default=0)),
                ('over_2', models.PositiveSmallIntegerField(default=0)),
                ('leave_00', models.PositiveIntegerField(default=0)),
                ('leave_01', models.PositiveIntegerField(default=0)),
                ('leave_10', models.PositiveIntegerField(default=0)),
                ('actual_salary', models.PositiveIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('one_third', models.PositiveSmallIntegerField(default=0, help_text='in hours')),
                ('two_third', models.PositiveSmallIntegerField(default=0, help_text='in hours')),
                ('double', models.PositiveSmallIntegerField(default=0, help_text='in hours')),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_time', models.FloatField(default=0, help_text='in hours')),
                ('total', models.FloatField(default=0, help_text='in days')),
                ('rate', models.FloatField(default=1)),
                ('category', models.CharField(choices=[('病假', 'Sick'), ('事假', 'Personal'), ('特休', 'Annual'), ('公假', 'Official'), ('喪假', 'Funeral'), ('婚假', 'Marriage'), ('生理假', 'Menstrual'), ('產前假', 'Maternity'), ('陪產假', 'Paternity'), ('職災病假', 'Injury'), ('其他', 'Other')], default='特休', max_length=64)),
                ('other_reason', models.CharField(blank=True, help_text='fill in when above is other', max_length=128, null=True)),
                ('special', models.TextField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('on_time', models.TimeField(default=django.utils.timezone.now)),
                ('off_time', models.TimeField(default=django.utils.timezone.now)),
                ('on_time_fixed', models.TimeField(blank=True, null=True)),
                ('off_time_fixed', models.TimeField(blank=True, null=True)),
                ('halfway', models.PositiveSmallIntegerField(default=0)),
                ('leave_early', models.PositiveSmallIntegerField(default=0)),
                ('fixed_note', models.CharField(blank=True, max_length=256, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
