# Generated by Django 3.1.2 on 2021-07-08 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('on_time', models.TimeField(default=django.utils.timezone.now)),
                ('off_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=256, unique=True)),
                ('passwd', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=128)),
                ('on_job', models.DateField(default=datetime.date.today)),
                ('salary', models.PositiveIntegerField()),
                ('annual', models.PositiveSmallIntegerField()),
                ('boss', models.BooleanField(default=False)),
                ('manager', models.BooleanField(default=False)),
                ('hr', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edited',
            fields=[
                ('origin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attendance.origin')),
                ('Note', models.TextField(blank=True, null=True)),
            ],
            bases=('attendance.origin',),
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2021)),
                ('month', models.PositiveIntegerField(default=7)),
                ('overtime', models.PositiveIntegerField(default=0)),
                ('delaytime', models.PositiveIntegerField(default=0)),
                ('leave_00', models.PositiveIntegerField(default=0)),
                ('leave_01', models.PositiveIntegerField(default=0)),
                ('leave_10', models.PositiveIntegerField(default=0)),
                ('actual_salary', models.PositiveIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddField(
            model_name='origin',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user'),
        ),
        migrations.CreateModel(
            name='Leave_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_time', models.PositiveIntegerField(default=0, help_text='in hours')),
                ('category', models.CharField(choices=[('病假', 'Sick'), ('事假', 'Personal'), ('特休', 'Annual'), ('公假', 'Official'), ('喪假', 'Funeral'), ('婚假', 'Marriage'), ('生理假', 'Menstrual'), ('產前假', 'Maternity'), ('陪產假', 'Paternity'), ('其他', 'Other')], default='特休', max_length=64)),
                ('other_reason', models.CharField(blank=True, help_text='fill in when above is other', max_length=128, null=True)),
                ('special', models.TextField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user')),
            ],
        ),
    ]
