# Generated by Django 3.1.2 on 2021-07-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='halfway',
            new_name='attend',
        ),
        migrations.AddField(
            model_name='daily',
            name='attend_fixed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daily',
            name='holiday',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daily',
            name='leave_early_fixed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daily',
            name='overtime',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daily',
            name='overtime_fixed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
