# Generated by Django 3.1.2 on 2021-07-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='total_leave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.total_leave'),
        ),
    ]
