# Generated by Django 3.1.2 on 2021-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
