# Generated by Django 3.1.2 on 2021-07-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='leave_early',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
