# Generated by Django 3.1.2 on 2021-07-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='month',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='total',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021),
        ),
    ]
