# Generated by Django 3.1.2 on 2021-07-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-year', '-month', 'start']},
        ),
        migrations.AlterField(
            model_name='daily',
            name='holiday',
            field=models.FloatField(default=0),
        ),
    ]
