# Generated by Django 3.1.2 on 2021-07-09 04:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210708_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('on_time', models.TimeField(default=django.utils.timezone.now)),
                ('off_time', models.TimeField(default=django.utils.timezone.now)),
                ('on_time_fixed', models.TimeField()),
                ('off_time_fixed', models.TimeField()),
                ('fixed_note', models.CharField(blank=True, max_length=256, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_time', models.PositiveSmallIntegerField(default=0, help_text='in hours')),
                ('category', models.CharField(choices=[('病假', 'Sick'), ('事假', 'Personal'), ('特休', 'Annual'), ('公假', 'Official'), ('喪假', 'Funeral'), ('婚假', 'Marriage'), ('生理假', 'Menstrual'), ('產前假', 'Maternity'), ('陪產假', 'Paternity'), ('其他', 'Other')], default='特休', max_length=64)),
                ('other_reason', models.CharField(blank=True, help_text='fill in when above is other', max_length=128, null=True)),
                ('special', models.TextField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user')),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('one_third', models.PositiveSmallIntegerField(default=0, help_text='in hours')),
                ('two_third', models.PositiveSmallIntegerField(default=0, help_text='in hours')),
                ('double', models.PositiveSmallIntegerField(default=0, help_text='in hours')),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='leave_form',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='origin',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='total',
            name='delaytime',
        ),
        migrations.RemoveField(
            model_name='total',
            name='overtime',
        ),
        migrations.AddField(
            model_name='total',
            name='over_13',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='total',
            name='over_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='total',
            name='over_23',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Edited',
        ),
        migrations.DeleteModel(
            name='Leave_form',
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
