# Generated by Django 3.1.2 on 2021-07-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210725_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='free_over',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='total',
            name='tax_over',
            field=models.FloatField(default=0),
        ),
    ]
