# Generated by Django 3.1.2 on 2021-07-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210709_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='annual',
        ),
        migrations.AddField(
            model_name='leave',
            name='total',
            field=models.PositiveSmallIntegerField(default=0, help_text='in days'),
        ),
        migrations.AddField(
            model_name='user',
            name='annual_left',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
