# Generated by Django 3.1.2 on 2021-07-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20210711_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='off_time_fixed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='on_time_fixed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.BooleanField(default=False),
        ),
    ]
