# Generated by Django 3.1.2 on 2021-07-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20210712_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
