# Generated by Django 3.1.2 on 2021-07-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20210712_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='overtime',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['on_job']},
        ),
        migrations.AddField(
            model_name='user',
            name='annual',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='family',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='health',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='labor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='retire_self',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='retirement',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
