# Generated by Django 3.1.2 on 2021-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20210716_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
