# Generated by Django 3.1.2 on 2021-07-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_user_self_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='halfway',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daily',
            name='leave_early',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
