# Generated by Django 3.1.2 on 2021-07-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20210716_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='rate',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leave',
            name='category',
            field=models.CharField(choices=[('病假', 'Sick'), ('事假', 'Personal'), ('特休', 'Annual'), ('公假', 'Official'), ('喪假', 'Funeral'), ('婚假', 'Marriage'), ('生理假', 'Menstrual'), ('產前假', 'Maternity'), ('陪產假', 'Paternity'), ('職災病假', 'Injury'), ('其他', 'Other')], default='特休', max_length=64),
        ),
    ]
